shopingkart/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>OutfitProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outfit</label>
        <referenceTo>Outfit__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

shopingkart/src/objects/Outfit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OutFit</relationshipLabel>
        <relationshipName>OutFit1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>OutFit</relationshipLabel>
        <relationshipName>OutFit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>conclusion</label>
        <picklist>
            <picklistValues>
                <fullName>Like</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dislike</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>STYLE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>STYLE</label>
        <referenceTo>STYLE__c</referenceTo>
        <relationshipLabel>OutFit</relationshipLabel>
        <relationshipName>OutFit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outfit</label>
    <nameField>
        <label>Outfit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OutFit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

shopingkart/src/objects/STYLE__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>STYLE</relationshipLabel>
        <relationshipName>STYLE</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>STYLE</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>STYLE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STYLE</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

shopingkart/src/classes/outfit.cls
public class outfit {
    public id accid{get;set;}
    public PageReference test() {
    system.debug('inside test'+prid);
        return null;
    }

    public id outfitid{get;set;}
    public PageReference updateoutfit() {

        outfit__c currentOutfitToUpdate=[select id from outfit__C where id=:outfitid];
        currentOutfitToUpdate.Result__c=result;
        system.debug('=========inside updateoutfit==result'+result);
        update currentOutfitToUpdate;
        return null;
    }
    list<outfit__c> Outfits;

    
    public list<outfit__c> getOutfits(){
            
            Outfits=[Select STYLE__c,Result__c,Name,  Opportunity__c,  Account__c, (Select Id, OpportunityId, SortOrder, PricebookEntryId, Product2Id, ProductCode, Name, Quantity, TotalPrice, UnitPrice, ListPrice, ServiceDate,  OutfitProduct__c From Opportunity_Product__r) From Outfit__c where account__c=:accid AND Result__c!=:'Send' ];
            Set<Id> resultIds = (new Map<Id,SObject>(Outfits)).keySet();
            system.debug('inside getmyoutfit============================================'+resultIds );
            system.debug('=========inside updateoutfit==result'+result);
            list<OpportunityLineItem> myOplI=[Select Product2Id,Balakrishna__OutfitProduct__c  From OpportunityLineItem where Balakrishna__OutfitProduct__c IN :resultIds ]; 
            system.debug('inside getmyoutfit  myOplI'+myOplI);  
    
    
    return outfits;
    }    
    
    
    
        public list<outfit__c> getOldOutfits(){
            
            Outfits=[Select STYLE__c,Result__c,Name,  Opportunity__c,  Account__c, (Select Id, OpportunityId, SortOrder, PricebookEntryId, Product2Id, ProductCode, Name, Quantity, TotalPrice, UnitPrice, ListPrice, ServiceDate,  OutfitProduct__c From Opportunity_Product__r) From Outfit__c where account__c=:accid AND Result__c=:'Send'];
            Set<Id> resultIds = (new Map<Id,SObject>(Outfits)).keySet();
            system.debug('inside getmyoutfit============================================'+resultIds );
       
            list<OpportunityLineItem> myOplI=[Select Product2Id,Balakrishna__OutfitProduct__c  From OpportunityLineItem where Balakrishna__OutfitProduct__c =: resultIds ]; 
            system.debug('inside getmyoutfit  myOplI'+myOplI);  
    
    
    return outfits;
    }   
        public outfit(){
        Outfits=new list<outfit__c>();
        }
        public string result{get;set;}
        public id prid{get;set;}
        private List<Id> photoIds;
        public List<Id> getphotos(){
        
            if(photoIds == null) {
                photoIds = new List<Id>();
                }
                photoIds.clear();

                system.debug('inside get photos'+prid);
                for(Attachment att : [select Id from Attachment where ParentId = :prid]) {
                    photoIds.Add(att.Id);
                }
            
                             
            return photoIds;
        }
    
}