shopingkart/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Parent_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Sub_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubOpportunityType__c</fullName>
        <label>SubOpportunityType</label>
        <picklist>
            <controllingField>Customer_OpportunityType__c</controllingField>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>auto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>visa</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

shopingkart/src/classes/subOpportunityController.cls
public class subOpportunityController {

   

    public ID myid{get;set;}
    public subOpportunityController(ApexPages.StandardController controller) {
    myid=ApexPages.currentPage().getParameters().get('id');
    system.debug('---------------------------------------id'+myid);
    }

    public subOpportunityController(){
       
            
    }
    public list<Opportunity> getOpportunities()
    {
    list<Opportunity> opps=new list<Opportunity>([select name,Amount,CloseDate,id,Parent_Opportunity__c,SubOpportunityType__c,ExpectedRevenue,ForecastCategoryName,LeadSource,NextStep,IsPrivate,Probability,TotalOpportunityQuantity,StageName from opportunity where Parent_Opportunity__c=:myid]);
    return opps;
        
    }
    public ID currentid{get;set;}
    public pageReference OppEdit()
    {
    currentid=ApexPages.currentPage().getParameters().get('Oppid');
    system.debug('-----------------------------------------------------linkid'+currentid+ApexPages.currentPage().getParameters().get('myid'));
    if(currentid!=null)
    {
    pageReference page=new pagereference('/apex/EditSubOpportunity?id='+ApexPages.currentPage().getParameters().get('Oppid'));
    return page;
    }
    return null;
    }
    public pageReference oppdelete()
    {
    
        currentid=ApexPages.currentPage().getParameters().get('oppid');
    system.debug('-----------------------------------------------------linkid'+currentid);
    if(currentid!=null)
    {
    opportunity opp=[select id from opportunity where id=:currentid];
    delete opp;
    }
    return null;
    }
    
    
}