shopingkart/src/objects/Outfit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OutFit</relationshipLabel>
        <relationshipName>OutFit1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>STYLE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>STYLE</label>
        <referenceTo>STYLE__c</referenceTo>
        <relationshipLabel>OutFit</relationshipLabel>
        <relationshipName>OutFit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outfit</label>
    <nameField>
        <label>Outfit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OutFit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

shopingkart/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>armani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>levi&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hugo boss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bluemint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>edition scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>marwood</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colour__c</fullName>
        <label>Colour</label>
        <picklist>
            <picklistValues>
                <fullName>Neutral5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blues5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dark5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earth5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pastel5</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

shopingkart/src/objects/Size__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Outfit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Top_Size__c</fullName>
        <label>Top Size</label>
        <picklist>
            <picklistValues>
                <fullName>i don&apos;t know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XXXL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WAIST__c</fullName>
        <label>WAIST</label>
        <picklist>
            <picklistValues>
                <fullName>I DON&apos;T KNOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>34L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>38S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>38R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>38L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>39S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>39R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>39L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>41S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>41R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>41L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42L</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Size</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Outfit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Size</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

shopingkart/src/objects/STYLE__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>STYLE</relationshipLabel>
        <relationshipName>STYLE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Tommyhilfiger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tedbaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reiss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RalphLauren</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paulsmith</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Levis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hackett</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>redperry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bluemint</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Budjet__c</fullName>
        <label>Budjet</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>i will pay for quality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Colour__c</fullName>
        <label>Colour</label>
        <picklist>
            <picklistValues>
                <fullName>Neutral5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blues5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dark5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earth5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pastel5</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Dimensions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dimensions</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Size__c.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Size__c</referenceTo>
        <relationshipLabel>STYLE</relationshipLabel>
        <relationshipName>STYLE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FavShirt__c</fullName>
        <label>favourite shirt style</label>
        <picklist>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casual</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Preferrence__c</fullName>
        <label>PreferrenceBox</label>
        <picklist>
            <picklistValues>
                <fullName>Whole Outfit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scarf</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blazer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knitwear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shoes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jacket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trouser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tshirt/Polo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shirt</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>TrouserFit__c</fullName>
        <label>Trouser_Fit</label>
        <picklist>
            <picklistValues>
                <fullName>Relaxed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slim</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>WorkStyle__c</fullName>
        <label>WorkStyle</label>
        <picklist>
            <picklistValues>
                <fullName>Casual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Casual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uniform</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>preferred_fit__c</fullName>
        <label>preferred fit</label>
        <picklist>
            <picklistValues>
                <fullName>Slim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extra Slim</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>regularstyle__c</fullName>
        <label>style</label>
        <picklist>
            <picklistValues>
                <fullName>Casual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trendy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Casual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urban</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preppy</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>STYLE</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>STYLE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>STYLE</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

shopingkart/src/classes/OutfiTCustomController.cls
public class OutfiTCustomController {

    public OutfiTCustomController(ApexPages.StandardController controller) {

    }

    
    public id Myid{get;set;}
    public Size__c mysize{get;set;}
    public STYLE__c mystyle1{get;set;}
    public void OutfiTCustomController()
    {    
        Myid=ApexPages.currentPage().getParameters().get('id') ;
        
        mystyle1=[Select  Name,    Id,     regularstyle__c,    preferred_fit__c,    WorkStyle__c,    TrouserFit__c, colour__c,   Preferrence__c,    FavShirt__c,    Dimensions__c,    Budjet__c,    Brand__c,    Account__c From   STYLE__c where id=:myid ];
        mysize=[Select   Name,  LastModifiedDate, Id,    WAIST__c,    Top_Size__c,    SHOES__c,    JACKET_SIZE__c,    HEIGHT__c,    COLLAR_SIZE__c,    Account__c From   Size__c where id=:mystyle1.Dimensions__c];
        Brand=mystyle1.Brand__c;
        searchStr='';
    }
    


    //=============================standardsetcontroller
    public List<Product2> getMyProductList()
    {
    
    List<Product2> MyProductList=setcon.getrecords();
    return MyProductList;
    }
    Public Integer noOfRecords{get;set;}
     public Apexpages.standardsetController setcon{
        get
        {
            if(setCon == null){
                
                
                String queryString = 'select id,Brand__c,Family,CreatedById,name,Colour__c,Demo__c from Product2';
                setcon = new apexpages.standardsetController(Database.getquerylocator(queryString));
                
                
                system.debug('===================================================='+setcon);
                setcon.setpagesize(5);
                noOfRecords=setcon.getResultsize();            }
                
            return setcon;
        }
         set;
        }
    
    
    
    
    
    //========================search
      public string Brand{get;set;}
      public List<SelectOption> getBrands() {
             List<SelectOption> options = new List<SelectOption>();
             Schema.DescribeFieldResult statusFieldDescription = STYLE__c.Brand__c.getDescribe();
             options.add(new SelectOption('--NONE--','--NONE--'));
                for (Schema.Picklistentry picklistEntry : statusFieldDescription.getPicklistValues())
                {
                    options.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
                }
         
           
            return options;   
       }
      public string Colour{get;set;}
      public List<SelectOption> getColours() {
             List<SelectOption> options = new List<SelectOption>();
             Schema.DescribeFieldResult statusFieldDescription = STYLE__c.Colour__c.getDescribe();
             options.add(new SelectOption('--NONE--','--NONE--'));
                for (Schema.Picklistentry picklistEntry : statusFieldDescription.getPicklistValues())
                {
                    options.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
                }
         
           
            return options;   
       } 
       public string family{get;set;}
      public List<SelectOption> getfamilys() {
             List<SelectOption> options = new List<SelectOption>();
             Schema.DescribeFieldResult statusFieldDescription = Product2.family.getDescribe();
             options.add(new SelectOption('--NONE--','--NONE--'));
                for (Schema.Picklistentry picklistEntry : statusFieldDescription.getPicklistValues())
                {
                    options.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
                }
         
           
            return options;   
       } 
      public string searchStr{get;set;} 
      public string Status{get;set;}  
      public string sortExpression{get;set;}
      public string Searchkey{get;set;}
      public string OrderString{get;set;}
      String PrevsortExpression{get;set;}
      Public pageReference Search()
      {
      string query;
      
      if(sortExpression==null)
      sortExpression='Name';
      if(PrevsortExpression==null)
      {
      PrevsortExpression=sortExpression;
      OrderString='ASC';
       system.debug('========================================OrderString'+OrderString+''+sortExpression+''+PrevsortExpression);
      
      }
      else
      {
          
              if(OrderString=='DESC'&&sortExpression==PrevsortExpression)
              {
              OrderString='ASC';
              system.debug('========================================OrderString==DESC&&sortExpression==PrevsortExpression'+OrderString+''+sortExpression+''+PrevsortExpression);
              }
              else
              if(sortExpression==PrevsortExpression)
              {
              OrderString='DESC';
              system.debug('========================================sortExpression==PrevsortExpression'+OrderString+''+sortExpression+''+PrevsortExpression);
              }else
              {
              OrderString='ASC';
              system.debug('========================================elseOrderString'+OrderString+''+sortExpression+''+PrevsortExpression);
              }
              
          system.debug('========================================OrderString'+OrderString+''+sortExpression+''+PrevsortExpression);
          PrevsortExpression=sortExpression;
      }    
          string filterstring;
      
       system.debug('========================================OrderString'+OrderString+''+sortExpression+''+PrevsortExpression);
    
       if(Status!=null&&Status!='--NONE--'&&Brand!=null&&Brand!='--NONE--')
       filterstring =' AND Brand__c =:Brand And Colour__c =:Status ';

      else
      if(Brand!=null&&Brand!='--NONE--')
      filterstring =' AND Brand__c =:Brand ';

      else
      if(Status!=null&&Status!='--NONE--')
      filterstring =' AND Colour__c =:Status ';
     if(filterstring==null)
     {
     filterstring=' ';
    
     //OrderString=' ';
     
     }
     string sortExp=' order by '+sortExpression;
      String searchStr =  Searchkey + '%';
      
      
      query='select id,Brand__c,Family ,CreatedById,name,Colour__c,Demo__c from Product2 where name like :searchStr '+filterstring+' '+sortExp+' '+OrderString;
      system.debug('======================================query'+query);
      system.debug('======================================query'+Database.getQueryLocator(query));
      setcon = new ApexPages.StandardSetController(Database.getQueryLocator(query));
      setcon.setpagesize(5);
    return null;
      
      }
      
      //=============================================
      Public Integer Count{get;set;}
      Public id Myproductid{get;set;}
      public pageReference Assign()
      {
      Outfit__c myOutfit=new Outfit__c();
      
      
      
      
      return null;
      }
      
}